name: Pull request
on:
  pull_request:
    types: ['opened', 'synchronize']
    branches: ["**"]


jobs:
  build-linux:
    name: Linux
    if: github.repository == 'servo/servo'
    uses: ./.github/workflows/linux.yml
    with:
      unit-tests: true